kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-llm-job
nodes:
  - role: control-plane
    extraPortMappings:
      # FastAPI backend
      - containerPort: 30800
        hostPort: 8000
        protocol: TCP
      # MinIO API
      - containerPort: 30900
        hostPort: 9000
        protocol: TCP
      # MinIO console
      - containerPort: 30901
        hostPort: 9001
        protocol: TCP
      # Prometheus
      - containerPort: 30909
        hostPort: 9090
        protocol: TCP
      # Grafana
      - containerPort: 30300
        hostPort: 3000
        protocol: TCP
